apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx # ini nama release
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx # in chartnya
      sourceRef:
        kind: HelmRepository # ini adaalah helm repository yang kita bikin di folder helm
        name: ingress-nginx
      interval: 1m

  